# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 18:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20160428_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 3, 18, 30, 30, 689983, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
